# Generate the dispatch layer of a TARGET=DYNAMIC build from the API symbol
# lists of the slices (see BlasfeoDynamicSlice.cmake).
#
# Invoked with cmake -P and the variables ('|'-separated lists):
#   ARCH        architecture group: X64, X86, ARMV8A or ARMV7A
#   FORMAT      object format: ELF, MACHO or COFF
#   TARGETS     slice targets, most preferred first
#   API_FILES   api.txt of each slice, same order
#   D_PS S_PS   panel sizes of each slice, same order
#   OUT_DIR     where to write the generated files
#
# Outputs:
#   blasfeo_dynamic_stubs.S    one public entry point per API symbol, jumping
#                              through blasfeo_dynamic_table (the only
#                              architecture specific part)
#   blasfeo_dynamic_table.inc  included by blasfeo_dynamic_dispatch.c: the
#                              targets and their panel sizes, the
#                              implementations of every slice, and the table,
#                              statically pointing to the last (most
#                              conservative) slice
#   blasfeo_dynamic.map        exports of a shared library: only the API, as
#   blasfeo_dynamic.exp        linker version script (ELF), exported symbols
#   blasfeo_dynamic.def        list (Mach-O) and module definition file (COFF)
#   blasfeo_dynamic_report.txt API symbols some slice lacks, and what replaces them
#
# A symbol a slice lacks is served by that slice's blasfeo_ref_ variant if any
# (same panel-major layout), otherwise by a stub aborting with a message.
# Implementations of another slice are never used: they assume another layout.

foreach(var TARGETS API_FILES D_PS S_PS)
	string(REPLACE "|" ";" ${var} "${${var}}")
endforeach()
list(LENGTH TARGETS narch)
math(EXPR last "${narch} - 1")

set(all "")
foreach(i RANGE ${last})
	list(GET API_FILES ${i} f)
	file(STRINGS ${f} syms)
	foreach(sym IN LISTS syms)
		set(has_${i}_${sym} 1)
	endforeach()
	list(APPEND all ${syms})
endforeach()
list(REMOVE_DUPLICATES all)
list(SORT all)
list(LENGTH all nsym)

# implementations
set(decls "")
set(missing "")
set(impl "")
set(report "")
foreach(i RANGE ${last})
	list(GET TARGETS ${i} target)
	set(impl_${i} "")
	foreach(sym IN LISTS all)
		string(REGEX REPLACE "^blasfeo_(hp_)?" "blasfeo_ref_" ref ${sym})
		if(has_${i}_${sym})
			set(fn blasfeo_dynamic${i}_${sym})
			string(APPEND decls "extern void ${fn}(void);\n")
		elseif(sym MATCHES "^blasfeo_" AND has_${i}_${ref})
			set(fn blasfeo_dynamic${i}_${ref})
			if(NOT declared_${fn})
				string(APPEND decls "extern void ${fn}(void);\n")
			endif()
			string(APPEND report "${target}: ${sym} -> ${ref}\n")
		else()
			set(fn blasfeo_dynamic_missing_${i}_${sym})
			string(APPEND missing "static void ${fn}(void) { blasfeo_dynamic_abort(\"${sym}\", ${i}); }\n")
			string(APPEND report "${target}: ${sym} -> abort\n")
		endif()
		set(declared_${fn} 1)
		string(APPEND impl_${i} "\t\t${fn},\n")
	endforeach()
	string(APPEND impl "\t{\n${impl_${i}}\t},\n")
endforeach()

string(REPLACE ";" "\", \"" targets_c "${TARGETS}")
string(REPLACE ";" ", " d_ps_c "${D_PS}")
string(REPLACE ";" ", " s_ps_c "${S_PS}")
list(GET D_PS ${last} d_ps_last)
list(GET S_PS ${last} s_ps_last)
file(WRITE ${OUT_DIR}/blasfeo_dynamic_table.inc
"// generated by cmake/BlasfeoDynamicGen.cmake, do not edit

#define BLASFEO_DYNAMIC_NSYM ${nsym}
#define BLASFEO_DYNAMIC_NARCH ${narch}
#define BLASFEO_DYNAMIC_DEFAULT_D_PS ${d_ps_last}
#define BLASFEO_DYNAMIC_DEFAULT_S_PS ${s_ps_last}

typedef void (*blasfeo_dynamic_fn)(void);

static const char *const dynamic_targets[BLASFEO_DYNAMIC_NARCH] = { \"${targets_c}\" };
static const int dynamic_d_ps[BLASFEO_DYNAMIC_NARCH] = { ${d_ps_c} };
static const int dynamic_s_ps[BLASFEO_DYNAMIC_NARCH] = { ${s_ps_c} };

${decls}
${missing}
// implementations of each slice, in the order of blasfeo_dynamic_table
static const blasfeo_dynamic_fn dynamic_impl[BLASFEO_DYNAMIC_NARCH][BLASFEO_DYNAMIC_NSYM] = {
${impl}};

// jump table, page aligned and padded so it can be made read-only alone;
// statically filled with the last slice, valid until the selection runs
#define BLASFEO_DYNAMIC_PAGE 4096
#define BLASFEO_DYNAMIC_NPAD ((BLASFEO_DYNAMIC_NSYM*sizeof(blasfeo_dynamic_fn)+BLASFEO_DYNAMIC_PAGE-1)/BLASFEO_DYNAMIC_PAGE*BLASFEO_DYNAMIC_PAGE/sizeof(blasfeo_dynamic_fn))
HIDDEN __attribute__((aligned(BLASFEO_DYNAMIC_PAGE)))
blasfeo_dynamic_fn blasfeo_dynamic_table[BLASFEO_DYNAMIC_NPAD] = {
${impl_${last}}};
")

if(FORMAT STREQUAL MACHO)
	set(us "_")
else()
	set(us "")
endif()

# public entry points: jump to blasfeo_dynamic_table[k];
# weak: all stubs share one object, unlike the one-object-per-routine archive
# of a regular build, where a routine the user also defines is simply not
# pulled in
if(ARCH STREQUAL X64)
	set(ptr 8)
	set(header "\t.text\n")
	set(align 4)
	# @OFFSET@: byte offset in the table
	set(body "\tendbr64\n\tjmp *${us}blasfeo_dynamic_table+@OFFSET@(%rip)\n")
elseif(ARCH STREQUAL X86)
	set(ptr 4)
	set(header "\t.text\n")
	set(align 4)
	# eax is not an argument register in the i386 calling convention
	string(CONCAT body
		"\tcall 1f\n"
		"1:\tpopl %eax\n"
		"\taddl $_GLOBAL_OFFSET_TABLE_+[.-1b], %eax\n"
		"\tjmp *blasfeo_dynamic_table@GOTOFF+@OFFSET@(%eax)\n")
elseif(ARCH STREQUAL ARMV8A AND FORMAT STREQUAL MACHO)
	set(ptr 8)
	set(header "\t.text\n")
	set(align 2)
	# scaled 12-bit offset of ldr: up to 4095 entries
	if(nsym GREATER 4095)
		message(FATAL_ERROR "Too many API symbols (${nsym}) for the Mach-O arm64 stubs")
	endif()
	string(CONCAT body
		"\tadrp x16, _blasfeo_dynamic_table@PAGE\n"
		"\tadd x16, x16, _blasfeo_dynamic_table@PAGEOFF\n"
		"\tldr x16, [x16, #@OFFSET@]\n"
		"\tbr x16\n")
elseif(ARCH STREQUAL ARMV8A)
	set(ptr 8)
	set(header "\t.text\n")
	set(align 2)
	# x16 (ip0) is the intra-procedure-call scratch register, as in PLT entries
	string(CONCAT body
		"\tadrp x16, blasfeo_dynamic_table+@OFFSET@\n"
		"\tldr x16, [x16, #:lo12:blasfeo_dynamic_table+@OFFSET@]\n"
		"\tbr x16\n")
elseif(ARCH STREQUAL ARMV7A)
	set(ptr 4)
	set(header "\t.syntax unified\n\t.arm\n\t.text\n")
	set(align 2)
	# ip (r12) is the intra-procedure-call scratch register, as in PLT
	# entries; pc reads 8 bytes ahead in ARM state; ldr pc interworks
	string(CONCAT body
		"\tldr ip, 2f\n"
		"1:\tadd ip, pc, ip\n"
		"\tldr pc, [ip]\n"
		"2:\t.word blasfeo_dynamic_table+@OFFSET@-(1b+8)\n")
else()
	message(FATAL_ERROR "Unknown ARCH ${ARCH}")
endif()

# no weak definitions in COFF: there, a stub clashes with a routine of the same
# name defined by the user when linking statically
set(stubs "")
set(offset 0)
foreach(sym IN LISTS all)
	string(REPLACE "@OFFSET@" "${offset}" b "${body}")
	if(FORMAT STREQUAL ELF)
		string(APPEND stubs
			"\t.weak ${sym}\n"
			"\t.type ${sym}, %function\n"
			"\t.p2align ${align}\n"
			"${sym}:\n"
			"${b}"
			"\t.size ${sym}, .-${sym}\n")
	elseif(FORMAT STREQUAL MACHO)
		string(APPEND stubs
			"\t.globl _${sym}\n"
			"\t.weak_definition _${sym}\n"
			"\t.p2align ${align}\n"
			"_${sym}:\n"
			"${b}")
	else()
		string(APPEND stubs
			"\t.globl ${sym}\n"
			"\t.def ${sym}; .scl 2; .type 32; .endef\n"
			"\t.p2align ${align}\n"
			"${sym}:\n"
			"${b}")
	endif()
	math(EXPR offset "${offset} + ${ptr}")
endforeach()
if(FORMAT STREQUAL ELF)
	set(footer "\t.section .note.GNU-stack,\"\",%progbits\n")
else()
	set(footer "")
endif()

file(WRITE ${OUT_DIR}/blasfeo_dynamic_stubs.S
"// generated by cmake/BlasfeoDynamicGen.cmake, do not edit

${header}
${stubs}
${footer}")

string(REPLACE ";" ";\n\t\t" exported "${all}")
file(WRITE ${OUT_DIR}/blasfeo_dynamic.map
"{
	global:
		${exported};
		blasfeo_d_ps;
		blasfeo_s_ps;
		blasfeo_dynamic_target;
	local:
		*;
};
")
string(REPLACE ";" "\n_" exported "${all}")
file(WRITE ${OUT_DIR}/blasfeo_dynamic.exp
"_${exported}
_blasfeo_d_ps
_blasfeo_s_ps
_blasfeo_dynamic_target
")
string(REPLACE ";" "\n\t" exported "${all}")
file(WRITE ${OUT_DIR}/blasfeo_dynamic.def
"EXPORTS
	${exported}
	blasfeo_d_ps DATA
	blasfeo_s_ps DATA
	blasfeo_dynamic_target
")

file(WRITE ${OUT_DIR}/blasfeo_dynamic_report.txt "${report}")
string(REGEX MATCHALL "-> blasfeo_ref_" nref "${report}")
string(REGEX MATCHALL "-> abort" nabort "${report}")
list(LENGTH nref nref)
list(LENGTH nabort nabort)
message(STATUS "BLASFEO dynamic: ${nsym} API symbols over ${narch} targets (${ARCH}, ${FORMAT}); "
	"${nref} slots served by a blasfeo_ref_ fallback, ${nabort} abort "
	"(see ${OUT_DIR}/blasfeo_dynamic_report.txt)")
